### ISSUE TITLE
iLO 2 Advanced is required for use

### ISSUE THREAD

**Issue by lyricnz** [scrapes/ILO2RemCon#13]
Got this working using
`java -XX:+ShowCodeDetailsInExceptionMessages -cp blah/ILO2-Standalone-Remote-Console/bin/main -Djava.security.properties=java.security Main`

I can see the BIOS/Boot screen, then it flashes to screen saying "iLO 2 Advanced is required for use".  Is this a HP/licensing issue?

**Comment by scrapes** [comment]
TL;DR yes.

ILO2 requires an advanced license to do anything after post on the KVM. Also features like power management are locked.

**Comment by lyricnz** [comment]
Fixed that, thanks.  Now running into lots of HP issues around support agreements required to download firmware for these ancient servers.  Time to throw the server out, I think :)
